---
repos:
    - repo: https://github.com/comkieffer/pre-commit-xmllint.git
      rev: 1.0.0
      hooks:
          - id: xmllint
            types: [file]
            files: \.(xlf|xml)$
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.38.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            exclude: ^\.yamllint$

    - repo: local
      hooks:
          - id: composer-validate
            name: composer validate
            entry: composer validate
            language: system
            files: composer\.(json|lock)$
            pass_filenames: false

          - id: php-lint
            name: php -l
            entry: php -l
            language: system
            files: \.php$

          - id: phpstan
            name: phpstan
            entry: vendor/bin/phpstan analyse --no-progress
            language: system
            files: \.(php|neon)$
            pass_filenames: false
