---
name: Deploy Staging Site

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        name: Build & Deploy Staging
        uses: ./.github/workflows/deploy-static-site.yaml
        with:
            environment: staging
            url: https://tssf-asia-pacific.github.io/communityobedience-staging/
            app_base_path: /communityobedience-staging/
            external_repository: TSSF-Asia-Pacific/communityobedience-staging
        secrets:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
