name: Build & Deploy Static Site Staging

on:
  workflow_dispatch:
  push:
    branches:
      - 'staging'

env:
  URL: tssf-asia-pacific.github.io/communityobedience-staging/

jobs:
  build:
    name: Build Static Site Staging
    runs-on: ubuntu-24.04
    environment:
      name: staging
      url: https://${{ env.URL }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn install

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: "8.2"
  
      - name: Run Makefile
        run: make all

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: TSSF-Asia-Pacific/communityobedience-staging
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
