name: Build Static Site

on: [push]

jobs:
  build:
    name: Build Static Site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install

    - name: Run Makefile
      run: make all

    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        branch: static-deploy
        commit_message: Update Static Site Branch