---
name: Update translations

on:
    workflow_dispatch:
    schedule:
        - cron: 37 * * * *

jobs:
    update-translations:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: master

            - name: Download Translations
              run: ./translations/download.sh
              env:
                  LOCALISE_KEY: ${{ secrets.LOCALISE_KEY }}

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Update translations
                  branch: master
                  commit_author: Github Action <actions@github.com>
